services:
  db:
    image: postgres:latest
    container_name: homework-assignment-db
    environment:
      POSTGRES_DB: HomeworkAssignmentDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - homework-assignment_network
              
  homework-assignment:
    image: homework-assignment.api
    container_name: homework-assignment-api
    build:
      context: .
      dockerfile: HomeworkAssignment.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=HomeworkAssignmentDb;Username=admin;Password=admin
    depends_on:
      - db
    networks:
      - homework-assignment_network

networks:
  homework-assignment_network:
    driver: bridge

  homeworkassignmentapi:
    image: homeworkassignmentapi
    build:
      context: .
      dockerfile: HomeworkAssignmentAPI/Dockerfile
